# Generated by Django 4.2.2 on 2023-09-12 13:08

import autoslug.fields
import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userRating', models.SmallIntegerField(default=0)),
                ('userAuthor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Tanks', 'Танки'), ('Healers', 'Хилы'), ('DamageDealers', 'ДД'), ('Merchants', 'Торговцы'), ('GuildMasters', 'Гилдмастеры'), ('QuestGivers', 'Квестгиверы'), ('BlackSmiths', 'Кузнецы'), ('Tanners', 'Кожевники'), ('PotionMakers', 'Зельевары'), ('SpellMasters', 'Мастера заклинаний')], max_length=15)),
                ('subscribers', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postDate', models.DateTimeField(auto_now_add=True)),
                ('postUpdate', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('preview_image', models.ImageField(upload_to='post_preview/')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
                ('postRating', models.SmallIntegerField(default=0)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='title')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poststable.author')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('commentDate', models.DateTimeField(auto_now_add=True)),
                ('comment_image', models.ImageField(default=None, null=True, upload_to='comment_images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_id', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='poststable.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, to='poststable.response'),
        ),
        migrations.AddField(
            model_name='post',
            name='likedUser',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='postCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poststable.category'),
        ),
    ]
