# Generated by Django 4.2.2 on 2023-09-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poststable', '0002_alter_response_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='comment_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='comment_images/'),
        ),
    ]
