# Generated by Django 4.2.2 on 2023-09-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poststable', '0003_alter_response_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
