# Generated by Django 4.2.2 on 2023-09-22 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poststable', '0004_response_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='likedUser',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response',
            name='responseRating',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
