# Generated by Django 4.2.2 on 2023-09-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poststable', '0005_response_likeduser_response_responserating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='preview_image',
            field=models.ImageField(upload_to='post_preview/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='response',
            name='comment_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='comment_images/%Y/%m/%d'),
        ),
    ]
